behaviors:
  SoccerTwos:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0001
      learning_rate_schedule: linear
      batch_size: 512
      buffer_size: 500000
      buffer_init_steps: 50000
      tau: 0.005
      steps_per_update: 5.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 50000
    self_play:
      save_steps: 100000
      team_change: 500000
      swap_steps: 5000
      window: 20
      play_against_latest_model_ratio: 0.3
      initial_elo: 1200.0

